import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Download, Calendar } from "lucide-react";
import jsPDF from "jspdf";

interface RTIData {
  applicantName: string;
  applicantAddress: string;
  applicantEmail: string;
  applicantPhone: string;
  authority: string;
  informationRequired: string;
}

interface RTILetter {
  letter: string;
  responseDeadline: string;
  appealDeadline: string;
}

export default function RTIAssistant() {
  const [rtiData, setRtiData] = useState<RTIData>({
    applicantName: "",
    applicantAddress: "",
    applicantEmail: "",
    applicantPhone: "",
    authority: "",
    informationRequired: "",
  });
  const [rtiLetter, setRtiLetter] = useState<RTILetter | null>(null);
  const [loading, setLoading] = useState(false);

  const generateRTILetter = () => {
    if (!rtiData.applicantName || !rtiData.authority || !rtiData.informationRequired) {
      alert("Please fill in all required fields");
      return;
    }

    setLoading(true);
    setTimeout(() => {
      const today = new Date();
      const responseDeadline = new Date(today);
      responseDeadline.setDate(responseDeadline.getDate() + 30);

      const appealDeadline = new Date(responseDeadline);
      appealDeadline.setDate(appealDeadline.getDate() + 30);

      const letter = `
RTI APPLICATION UNDER RIGHT TO INFORMATION ACT, 2005

Date: ${today.toLocaleDateString()}

To,
The Public Information Officer,
${rtiData.authority}

Subject: RTI Application for Information

Dear Sir/Madam,

I, ${rtiData.applicantName}, hereby submit this application under the Right to Information Act, 2005, to seek the following information:

${rtiData.informationRequired}

I request that the above information be provided to me in the format as specified in the RTI Act, 2005.

As per Section 7 of the RTI Act, 2005, I request that this information be provided within 30 days from the date of receipt of this application.

Applicant Details:
Name: ${rtiData.applicantName}
Address: ${rtiData.applicantAddress}
Email: ${rtiData.applicantEmail}
Phone: ${rtiData.applicantPhone}

I am prepared to pay any fee as prescribed under the RTI Act, 2005.

Yours faithfully,

${rtiData.applicantName}
      `.trim();

      setRtiLetter({
        letter,
        responseDeadline: responseDeadline.toLocaleDateString(),
        appealDeadline: appealDeadline.toLocaleDateString(),
      });
      setLoading(false);
    }, 800);
  };

  const exportPDF = () => {
    if (!rtiLetter) return;

    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    let yPos = 20;

    // Header
    doc.setFontSize(18);
    doc.setTextColor(30, 64, 175);
    doc.text("RTI Application Letter", 20, yPos);
    yPos += 12;

    // Date
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(`Generated: ${new Date().toLocaleDateString()}`, 20, yPos);
    yPos += 10;

    // Letter Content
    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    const letterLines = doc.splitTextToSize(rtiLetter.letter, pageWidth - 40);
    doc.text(letterLines, 20, yPos);
    yPos += letterLines.length * 5 + 10;

    if (yPos > pageHeight - 40) {
      doc.addPage();
      yPos = 20;
    }

    // Important Dates
    doc.setFontSize(12);
    doc.setTextColor(30, 64, 175);
    doc.text("Important Dates:", 20, yPos);
    yPos += 8;

    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    doc.text(`Response Deadline: ${rtiLetter.responseDeadline}`, 20, yPos);
    yPos += 6;
    doc.text(`First Appeal Deadline: ${rtiLetter.appealDeadline}`, 20, yPos);
    yPos += 12;

    // Instructions
    doc.setFontSize(11);
    doc.setTextColor(30, 64, 175);
    doc.text("How to Submit:", 20, yPos);
    yPos += 8;

    const instructions = [
      "1. Print this letter on plain paper",
      "2. Sign and date the letter",
      "3. Submit to the Public Information Officer (PIO) of the concerned authority",
      "4. Keep a copy for your records",
      "5. Request an acknowledgement receipt",
    ];

    doc.setFontSize(9);
    doc.setTextColor(0, 0, 0);
    instructions.forEach((instruction) => {
      doc.text(instruction, 20, yPos);
      yPos += 5;
    });

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      "This letter is generated by CivicShield. For legal advice, consult with a lawyer.",
      pageWidth / 2,
      pageHeight - 10,
      { align: "center" }
    );

    doc.save("CivicShield_RTI_Application.pdf");
  };

  return (
    <div className="max-w-4xl mx-auto">
      <div className="mb-8">
        <h1 className="text-4xl font-bold text-gray-900 mb-2">RTI Assistant</h1>
        <p className="text-lg text-gray-600 font-light">
          Generate RTI applications, calculate response deadlines, and auto-draft
          First Appeal letters
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Input Form */}
        <div className="lg:col-span-2 space-y-6">
          <Card className="p-6">
            <h2 className="text-xl font-bold text-gray-900 mb-4">
              RTI Application Details
            </h2>

            <div className="space-y-4">
              <div>
                <label className="block text-sm font-semibold text-gray-700 mb-2">
                  Your Full Name *
                </label>
                <Input
                  placeholder="e.g., Rajesh Kumar"
                  value={rtiData.applicantName}
                  onChange={(e) =>
                    setRtiData({ ...rtiData, applicantName: e.target.value })
                  }
                  className="w-full"
                />
              </div>

              <div>
                <label className="block text-sm font-semibold text-gray-700 mb-2">
                  Your Address
                </label>
                <Input
                  placeholder="e.g., 123 Main Street, Delhi 110001"
                  value={rtiData.applicantAddress}
                  onChange={(e) =>
                    setRtiData({ ...rtiData, applicantAddress: e.target.value })
                  }
                  className="w-full"
                />
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-semibold text-gray-700 mb-2">
                    Email
                  </label>
                  <Input
                    type="email"
                    placeholder="your@email.com"
                    value={rtiData.applicantEmail}
                    onChange={(e) =>
                      setRtiData({ ...rtiData, applicantEmail: e.target.value })
                    }
                    className="w-full"
                  />
                </div>
                <div>
                  <label className="block text-sm font-semibold text-gray-700 mb-2">
                    Phone
                  </label>
                  <Input
                    placeholder="9876543210"
                    value={rtiData.applicantPhone}
                    onChange={(e) =>
                      setRtiData({ ...rtiData, applicantPhone: e.target.value })
                    }
                    className="w-full"
                  />
                </div>
              </div>

              <div>
                <label className="block text-sm font-semibold text-gray-700 mb-2">
                  Government Authority *
                </label>
                <Input
                  placeholder="e.g., Ministry of Health, Delhi Municipal Corporation"
                  value={rtiData.authority}
                  onChange={(e) =>
                    setRtiData({ ...rtiData, authority: e.target.value })
                  }
                  className="w-full"
                />
              </div>

              <div>
                <label className="block text-sm font-semibold text-gray-700 mb-2">
                  Information Required *
                </label>
                <Textarea
                  placeholder="Describe the specific information you want to request. Be as detailed as possible."
                  value={rtiData.informationRequired}
                  onChange={(e) =>
                    setRtiData({
                      ...rtiData,
                      informationRequired: e.target.value,
                    })
                  }
                  className="w-full min-h-48"
                />
              </div>

              <Button
                onClick={generateRTILetter}
                disabled={loading}
                className="w-full bg-blue-600 hover:bg-blue-700 text-white font-semibold py-6"
              >
                {loading ? "Generating Letter..." : "Generate RTI Letter"}
              </Button>
            </div>
          </Card>
        </div>

        {/* Results */}
        <div className="lg:col-span-1">
          {rtiLetter && (
            <Card className="p-6 sticky top-24">
              <h2 className="text-xl font-bold text-gray-900 mb-4">
                Your RTI Letter
              </h2>

              {/* Preview */}
              <div className="mb-4 p-4 bg-gray-50 rounded-lg border border-gray-200 max-h-64 overflow-y-auto">
                <p className="text-xs text-gray-700 whitespace-pre-wrap font-mono">
                  {rtiLetter.letter.substring(0, 300)}...
                </p>
              </div>

              {/* Deadlines */}
              <div className="space-y-3 mb-6">
                <div className="p-3 bg-blue-50 rounded-lg border border-blue-200">
                  <p className="text-xs font-semibold text-blue-900 mb-1">
                    Response Deadline
                  </p>
                  <p className="text-sm font-bold text-blue-700 flex items-center gap-2">
                    <Calendar className="w-4 h-4" />
                    {rtiLetter.responseDeadline}
                  </p>
                </div>

                <div className="p-3 bg-orange-50 rounded-lg border border-orange-200">
                  <p className="text-xs font-semibold text-orange-900 mb-1">
                    Appeal Deadline
                  </p>
                  <p className="text-sm font-bold text-orange-700 flex items-center gap-2">
                    <Calendar className="w-4 h-4" />
                    {rtiLetter.appealDeadline}
                  </p>
                </div>
              </div>

              {/* Export Button */}
              <Button
                onClick={exportPDF}
                className="w-full bg-orange-600 hover:bg-orange-700 text-white font-semibold"
              >
                <Download className="w-4 h-4 mr-2" />
                Export PDF
              </Button>
            </Card>
          )}
        </div>
      </div>
    </div>
  );
}
